# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ."
  bin = "tmp/main"
  watch_ext = ["go", "html", "css"]
  watch_dir = ["."]
  exclude_dir = ["tmp", ".git"]

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  log = "white"
